from datetime import datetime


DEMO_ACTIVITIES = [
    {
        "id": 1,
        "title": "梧桐街区建筑漫步",
        "description": "从武康路出发，用两个小时重新认识上海老街区的建筑细节与城市故事。",
        "detail": "领队会沿途介绍里弄、花园住宅和街角小店的变迁，并安排两次自由观察与速写时间。无需建筑知识，适合想慢下来探索城市的人。",
        "start_time": datetime(2026, 6, 6, 9, 30),
        "city": "上海市",
        "location": "徐汇区武康路 393 号 · 武康大楼前集合",
        "max_participants": 20,
        "initial_participants": 11,
        "fee": 0,
        "tags": "城市探索",
        "preparation": "穿适合步行的鞋；自备饮用水；可选带速写本或相机。",
        "image": "/static/images/activities/historic-lane-walk.webp",
    },
    {
        "id": 2,
        "title": "周末城市摄影散步",
        "description": "沿徐汇滨江寻找光影、建筑线条和日常瞬间，练习街头摄影的观察方法。",
        "detail": "活动包括拍摄思路分享、滨江实拍和收尾交流。手机与相机都可以参加，重点是构图、光线和如何自然地记录城市。",
        "start_time": datetime(2026, 6, 6, 15, 0),
        "city": "上海市",
        "location": "徐汇区龙腾大道 3398 号 · 龙美术馆西岸馆入口",
        "max_participants": 28,
        "initial_participants": 18,
        "fee": 0,
        "tags": "影像摄影",
        "preparation": "带手机或相机；提前充满电；建议穿舒适步行鞋；自备饮用水。",
        "image": "/static/images/activities/city-photo-walk.webp",
    },
    {
        "id": 3,
        "title": "手冲咖啡风味入门体验",
        "description": "从闻香、研磨到注水，认识不同产区咖啡豆的风味差异，完成自己的第一杯手冲。",
        "detail": "咖啡师会示范基础器具使用和三段式注水，再由每位参与者独立练习。现场准备三款豆子进行对比品鉴。",
        "start_time": datetime(2026, 6, 7, 10, 30),
        "city": "上海市",
        "location": "静安区愚园路 546 号 · 二楼咖啡实验室",
        "max_participants": 16,
        "initial_participants": 12,
        "fee": 68,
        "tags": "咖啡茶饮",
        "preparation": "无需自带器具；建议活动前一小时避免饮用浓咖啡；如对咖啡因敏感请提前说明。",
        "image": "/static/images/activities/coffee-workshop.webp",
    },
    {
        "id": 4,
        "title": "黄昏江畔轻跑小组",
        "description": "适合新手的滨江轻松跑，控制在可聊天的节奏，一起完成 5 公里。",
        "detail": "集合后先做动态热身，再沿浦东滨江慢跑，途中设置补水和拉伸节点。活动不追求配速，第一次参加跑团也没有压力。",
        "start_time": datetime(2026, 6, 3, 19, 0),
        "city": "上海市",
        "location": "浦东新区滨江大道 1777 号 · 望江驿 2 号驿站",
        "max_participants": 35,
        "initial_participants": 24,
        "fee": 0,
        "tags": "运动户外",
        "preparation": "穿跑鞋和透气运动服；自备饮用水；有旧伤请提前告知领队。",
        "image": "/static/images/activities/riverside-run.webp",
    },
    {
        "id": 5,
        "title": "独立电影放映与交流夜",
        "description": "在小剧场观看一部当代独立电影，映后围绕叙事、镜头和城市经验展开交流。",
        "detail": "活动包含完整放映和约四十分钟映后讨论。主持人会提供几个开放问题，欢迎带着不同理解参与，不需要专业影评背景。",
        "start_time": datetime(2026, 6, 5, 19, 30),
        "city": "上海市",
        "location": "长宁区新华路 345 弄 8 号 · 新华社区小剧场",
        "max_participants": 45,
        "initial_participants": 31,
        "fee": 35,
        "tags": "观影戏剧",
        "preparation": "请提前十分钟入场；场内请将手机调至静音；可自带纸笔记录。",
        "image": "/static/images/activities/indie-film-night.webp",
    },
    {
        "id": 6,
        "title": "零基础陶艺手捏工作坊",
        "description": "用陶土制作一只属于自己的小碗或杯子，在慢节奏手作里放松一个下午。",
        "detail": "老师会讲解揉泥、塑形和表面装饰方法。完成后的作品由工作室统一上釉烧制，约两周后可到店领取。",
        "start_time": datetime(2026, 6, 6, 13, 30),
        "city": "上海市",
        "location": "长宁区愚园路 1088 弄 32 号 · 慢慢做工作室",
        "max_participants": 14,
        "initial_participants": 9,
        "fee": 128,
        "tags": "手作艺术",
        "preparation": "建议穿耐脏衣物；指甲不宜过长；工具和围裙由工作室提供。",
        "image": "/static/images/activities/pottery-workshop.webp",
    },
    {
        "id": 7,
        "title": "新手友好桌游社交局",
        "description": "不需要熟悉规则，现场带玩轻策略与合作类桌游，适合认识新朋友。",
        "detail": "主持人会根据人数分桌，先从规则简单的破冰游戏开始，再进入合作或轻策略桌游。可以随时换桌体验不同玩法。",
        "start_time": datetime(2026, 6, 3, 19, 0),
        "city": "上海市",
        "location": "黄浦区西藏中路 268 号 · 来福士广场附近桌游馆",
        "max_participants": 24,
        "initial_participants": 16,
        "fee": 45,
        "tags": "游戏桌游",
        "preparation": "无需自带桌游；请准时到场方便分组；费用包含场地和一杯饮品。",
        "image": "/static/images/activities/board-game-social.webp",
    },
]
