"""add unique constraint to registration

Revision ID: 910bb336a36d
Revises: 52ce70c39825
Create Date: 2026-06-04 02:03:22.725340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910bb336a36d'
down_revision = '52ce70c39825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_registration_user_activity', ['user_id', 'activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint('uq_registration_user_activity', type_='unique')

    # ### end Alembic commands ###
